import React, { useState, useRef, useEffect } from 'react';
import { Send, Bot, User, Loader2, Sparkles, Building2, Briefcase } from 'lucide-react';
import { collection, getDocs } from 'firebase/firestore';
import { db } from './lib/firebase';
import ReactMarkdown from 'react-markdown';

type Message = {
  role: 'user' | 'model';
  parts: { text: string }[];
};

export default function ChatApp() {
  const [messages, setMessages] = useState<Message[]>([
    { role: 'model', parts: [{ text: 'Olá! Sou o Assistente DP. Como posso ajudar com suas dúvidas sobre as empresas, sindicatos e rotinas de departamento pessoal hoje?' }] }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [contextData, setContextData] = useState<{empresas: any[], sindicatos: any[]}>({ empresas: [], sindicatos: [] });
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const fetchContextData = async () => {
      try {
        const empresasSnap = await getDocs(collection(db, 'empresas'));
        const empresas = empresasSnap.docs.map(d => ({ id: d.id, ...d.data() }));
        
        const sindicatosSnap = await getDocs(collection(db, 'sindicatos'));
        const sindicatos = sindicatosSnap.docs.map(d => ({ id: d.id, ...d.data() }));
        
        setContextData({ empresas, sindicatos });
      } catch (err) {
        console.error("Erro ao carregar contexto para IA:", err);
      }
    };
    fetchContextData();
  }, []);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userMessage: Message = { role: 'user', parts: [{ text: input.trim() }] };
    const newMessages = [...messages, userMessage];
    setMessages(newMessages);
    setInput('');
    setIsLoading(true);

    try {
      // Omit the first greeting from history sent to API as it wasn't actually generated by the model
      const historyToSend = newMessages.slice(1);

      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'x-api-key': import.meta.env.VITE_API_SECRET_KEY || ''
        },
        body: JSON.stringify({ 
          history: historyToSend,
          context: contextData
        })
      });

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error || 'Erro na comunicação com a IA.');
      }

      const resData = await response.json();
      setMessages([...newMessages, { role: 'model', parts: [{ text: resData.text }] }]);
    } catch (error: any) {
      console.error(error);
      setMessages([...newMessages, { 
        role: 'model', 
        parts: [{ text: `Desculpe, ocorreu um erro: ${error.message}` }] 
      }]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 rounded-xl overflow-hidden border border-slate-800 shadow-xl relative">
      {/* Background Decorator */}
      <div className="absolute top-0 right-0 p-32 opacity-5 pointer-events-none">
        <Sparkles className="w-64 h-64 text-indigo-400" />
      </div>

      <div className="bg-slate-950 p-6 border-b border-slate-800 flex items-center justify-between z-10 relative">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-indigo-500/20 rounded-xl">
            <Bot className="w-7 h-7 text-indigo-400" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white tracking-tight">Assistente DP</h2>
            <p className="text-sm text-slate-400">Inteligência Artificial conectada aos seus dados</p>
          </div>
        </div>
        <div className="flex items-center gap-3 text-xs text-slate-500 font-medium">
           <div className="flex items-center gap-1.5"><Building2 className="w-3.5 h-3.5"/> {contextData.empresas.length} Empresas</div>
           <div className="flex items-center gap-1.5"><Briefcase className="w-3.5 h-3.5"/> {contextData.sindicatos.length} Sindicatos</div>
        </div>
      </div>
      
      <div className="flex-1 overflow-y-auto p-6 space-y-6 z-10 relative scrollbar-thin scrollbar-thumb-slate-700 scrollbar-track-transparent">
        {messages.map((msg, idx) => (
          <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`flex max-w-[80%] gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
              <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center mt-1 ${
                msg.role === 'user' ? 'bg-indigo-600' : 'bg-slate-800 border border-slate-700'
              }`}>
                {msg.role === 'user' ? <User className="w-4 h-4 text-white" /> : <Bot className="w-4 h-4 text-indigo-400" />}
              </div>
              <div className={`px-5 py-3.5 rounded-2xl ${
                msg.role === 'user' 
                  ? 'bg-indigo-600 text-white rounded-tr-sm' 
                  : 'bg-slate-800 text-slate-200 rounded-tl-sm shadow-sm border border-slate-700/50'
              }`}>
                {msg.role === 'model' ? (
                  <div className="prose prose-invert prose-sm max-w-none prose-p:leading-relaxed prose-pre:bg-slate-900 prose-pre:border prose-pre:border-slate-700">
                    <ReactMarkdown>{msg.parts[0].text}</ReactMarkdown>
                  </div>
                ) : (
                  <p className="whitespace-pre-wrap leading-relaxed">{msg.parts[0].text}</p>
                )}
              </div>
            </div>
          </div>
        ))}
        {isLoading && (
          <div className="flex justify-start">
            <div className="flex max-w-[80%] gap-3 flex-row">
              <div className="flex-shrink-0 w-8 h-8 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center mt-1">
                <Bot className="w-4 h-4 text-indigo-400" />
              </div>
              <div className="px-5 py-4 bg-slate-800 text-slate-200 rounded-2xl rounded-tl-sm shadow-sm border border-slate-700/50 flex items-center gap-2">
                <Loader2 className="w-4 h-4 animate-spin text-indigo-400" />
                <span className="text-sm font-medium text-slate-400">Processando...</span>
              </div>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      <div className="p-4 bg-slate-950 border-t border-slate-800 z-10 relative">
        <form onSubmit={handleSend} className="max-w-4xl mx-auto relative flex items-end gap-2">
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                handleSend(e);
              }
            }}
            placeholder="Pergunte sobre as empresas, sindicatos, regras trabalhistas..."
            className="w-full bg-slate-900 border border-slate-700 text-white rounded-xl px-4 py-3.5 pr-12 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 resize-none min-h-[52px] max-h-32 scrollbar-thin transition-colors text-sm"
            rows={1}
            style={{ 
              height: 'auto',
              // Auto-resize hack conceptually
            }}
            onInput={(e) => {
              const target = e.target as HTMLTextAreaElement;
              target.style.height = 'auto';
              target.style.height = Math.min(target.scrollHeight, 128) + 'px';
            }}
          />
          <button
            type="submit"
            disabled={!input.trim() || isLoading}
            className="absolute right-2 bottom-2 p-2 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-700 disabled:text-slate-500 text-white rounded-lg transition-colors flex items-center justify-center"
          >
            <Send className="w-4 h-4" />
          </button>
        </form>
      </div>
    </div>
  );
}
