import React, { useState, useRef, useEffect } from 'react';
import { Send, Bot, User, Loader2, Sparkles, Building2, Briefcase, CheckCircle2 } from 'lucide-react';
import { collection, getDocs, addDoc } from 'firebase/firestore';
import { db } from './lib/firebase';
import ReactMarkdown from 'react-markdown';

type Message = {
  role: 'user' | 'model';
  parts: { text: string }[];
  proposedAction?: any;
  metadata?: any;
};

export default function ChatApp() {
  const [messages, setMessages] = useState<Message[]>([
    { role: 'model', parts: [{ text: 'Olá! Sou o Assistente DP. Como posso ajudar com suas dúvidas sobre as empresas, sindicatos e rotinas de departamento pessoal hoje?' }] }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [contextData, setContextData] = useState<{empresas: any[], sindicatos: any[]}>({ empresas: [], sindicatos: [] });
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const [actionFeedback, setActionFeedback] = useState<string | null>(null);

  useEffect(() => {
    const fetchContextData = async () => {
      try {
        const empresasSnap = await getDocs(collection(db, 'empresas'));
        const empresas = empresasSnap.docs.map(d => ({ id: d.id, ...d.data() }));
        
        const sindicatosSnap = await getDocs(collection(db, 'sindicatos'));
        const sindicatos = sindicatosSnap.docs.map(d => ({ id: d.id, ...d.data() }));
        
        setContextData({ empresas, sindicatos });
      } catch (err) {
        console.error("Erro ao carregar contexto para IA:", err);
      }
    };
    fetchContextData();
  }, []);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userMessage: Message = { role: 'user', parts: [{ text: input.trim() }] };
    const newMessages = [...messages, userMessage];
    setMessages(newMessages);
    setInput('');
    setIsLoading(true);
    setActionFeedback(null);

    try {
      // Omit the first greeting from history sent to API as it wasn't actually generated by the model
      const historyToSend = newMessages.slice(1);

      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'x-api-key': import.meta.env.VITE_API_SECRET_KEY || ''
        },
        body: JSON.stringify({ 
          history: historyToSend,
          context: contextData
        })
      });

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error || 'Erro na comunicação com a IA.');
      }

      const resData = await response.json();
      
      let newModelMsg: Message = { 
        role: 'model', 
        parts: [{ text: resData.text || '' }],
        metadata: resData.metadata
      };

      if (resData.proposedAction && resData.proposedAction.intent !== 'UNKNOWN') {
        newModelMsg.proposedAction = resData.proposedAction;
      }

      setMessages([...newMessages, newModelMsg]);
    } catch (error: any) {
      console.error(error);
      setMessages([...newMessages, { 
        role: 'model', 
        parts: [{ text: `Desculpe, ocorreu um erro: ${error.message}` }] 
      }]);
    } finally {
      setIsLoading(false);
      setTimeout(() => setActionFeedback(null), 3000);
    }
  };

  const handleConfirmAction = async (msgIndex: number) => {
    const msg = messages[msgIndex];
    if (!msg.proposedAction) return;

    setIsLoading(true);
    try {
      const { intent, parameters } = msg.proposedAction;
      const sanitizedParameters = Object.fromEntries(
        Object.entries(parameters || {}).filter(([_, v]) => v !== undefined)
      );

      if (intent === 'CREATE_CALENDAR_EVENT') {
        let eventDate = sanitizedParameters.date;
        if (typeof eventDate === 'string') {
           eventDate = parseInt(eventDate);
        } else if (!eventDate) {
           eventDate = Date.now();
        }

        let empresaNome = '';
        if (sanitizedParameters.empresaId) {
          const emp = contextData.empresas.find(e => e.id === sanitizedParameters.empresaId);
          if (emp) empresaNome = emp.nome;
          else {
            const sind = contextData.sindicatos.find(s => s.id === sanitizedParameters.empresaId);
            if (sind) empresaNome = sind.nome;
          }
        }

        await addDoc(collection(db, 'calendarEvents'), {
          ...sanitizedParameters,
          date: eventDate,
          empresaNome: empresaNome,
          isRecurrent: false,
          status: 'ATIVO',
          createdAt: Date.now()
        });
        setActionFeedback('Lembrete criado com sucesso!');
      } else if (intent === 'CREATE_CHECKLIST_RULE') {
        await addDoc(collection(db, 'checklistRules'), {
          ...sanitizedParameters,
          createdAt: Date.now()
        });
        setActionFeedback('Regra de checklist criada com sucesso!');
      }

      // Hide buttons by removing proposedAction
      const newMessages = [...messages];
      newMessages[msgIndex] = { ...msg, proposedAction: undefined };
      setMessages(newMessages);

    } catch (error) {
      console.error("Erro ao executar ação:", error);
      setActionFeedback('Erro ao criar ação.');
    } finally {
      setIsLoading(false);
      setTimeout(() => setActionFeedback(null), 3000);
    }
  };

  const handleRejectAction = (msgIndex: number) => {
    const newMessages = [...messages];
    newMessages[msgIndex] = { ...messages[msgIndex], proposedAction: undefined };
    setMessages(newMessages);
  };

  return (
    <div className="flex flex-col flex-1 h-full w-full relative">
      <div className="mb-6 flex items-center justify-between z-10 relative">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-indigo-500/20 rounded-xl">
            <Bot className="w-7 h-7 text-indigo-400" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white tracking-tight">Assistente DP</h2>
            <p className="text-sm text-slate-400">Inteligência Artificial conectada aos seus dados</p>
          </div>
        </div>
      </div>
      
      <div className="flex-1 overflow-y-auto space-y-6 z-10 relative scrollbar-thin scrollbar-thumb-slate-700 scrollbar-track-transparent pr-4">
        {messages.map((msg, idx) => (
          <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`flex max-w-[90%] gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
              <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center mt-1 ${
                msg.role === 'user' ? 'bg-indigo-600' : 'bg-slate-800 border border-slate-700'
              }`}>
                {msg.role === 'user' ? <User className="w-4 h-4 text-white" /> : <Bot className="w-4 h-4 text-indigo-400" />}
              </div>
              <div className={`px-5 py-3.5 rounded-2xl ${
                msg.role === 'user' 
                  ? 'bg-indigo-600 text-white rounded-tr-sm' 
                  : 'bg-slate-800 text-slate-200 rounded-tl-sm shadow-sm border border-slate-700/50'
              }`}>
                {msg.role === 'model' ? (
                  <>
                    <div className="prose prose-invert prose-sm max-w-none break-words prose-p:leading-relaxed prose-pre:bg-slate-900 prose-pre:border prose-pre:border-slate-700">
                      <ReactMarkdown>{msg.parts[0].text}</ReactMarkdown>
                    </div>
                    {msg.proposedAction && (
                      <div className="mt-4 flex gap-3">
                        <button
                          onClick={() => handleConfirmAction(idx)}
                          className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-medium rounded-lg transition-colors flex items-center gap-2"
                        >
                          <CheckCircle2 className="w-4 h-4" />
                          Sim, confirmar
                        </button>
                        <button
                          onClick={() => handleRejectAction(idx)}
                          className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white text-sm font-medium rounded-lg transition-colors"
                        >
                          Não, cancelar
                        </button>
                      </div>
                    )}
                    {msg.metadata && (
                      <div className="mt-3 text-[10px] text-slate-500 font-medium">
                        Extraída após {msg.metadata.attempts} tentativa(s) pelo modelo {msg.metadata.model}.
                      </div>
                    )}
                  </>
                ) : (
                  <p className="whitespace-pre-wrap leading-relaxed">{msg.parts[0].text}</p>
                )}
              </div>
            </div>
          </div>
        ))}
        {isLoading && (
          <div className="flex justify-start">
            <div className="flex max-w-[90%] gap-3 flex-row">
              <div className="flex-shrink-0 w-8 h-8 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center mt-1">
                <Bot className="w-4 h-4 text-indigo-400" />
              </div>
              <div className="px-5 py-4 bg-slate-800 text-slate-200 rounded-2xl rounded-tl-sm shadow-sm border border-slate-700/50 flex items-center gap-2">
                <Loader2 className="w-4 h-4 animate-spin text-indigo-400" />
                <span className="text-sm font-medium text-slate-400">Processando...</span>
              </div>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      <div className="mt-4 pt-4 border-t border-slate-800/50 z-10 relative">
        {actionFeedback && (
          <div className="absolute -top-10 left-0 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 px-3 py-1.5 rounded-lg text-xs flex items-center gap-2 animate-in fade-in slide-in-from-bottom-2">
            <CheckCircle2 className="w-3.5 h-3.5" />
            {actionFeedback}
          </div>
        )}
        <form onSubmit={handleSend} className="relative flex items-end gap-2">
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                handleSend(e);
              }
            }}
            placeholder="Pergunte sobre as empresas, sindicatos, regras trabalhistas..."
            className="w-full bg-slate-950 border border-slate-700 text-white rounded-xl px-4 py-3.5 pr-12 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 resize-none min-h-[60px] max-h-32 scrollbar-thin transition-colors text-sm shadow-inner"
            rows={1}
            style={{ height: 'auto' }}
            onInput={(e) => {
              const target = e.target as HTMLTextAreaElement;
              target.style.height = 'auto';
              target.style.height = Math.min(target.scrollHeight, 128) + 'px';
            }}
          />
          <button
            type="submit"
            disabled={!input.trim() || isLoading}
            className="absolute right-2 bottom-2 p-2 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 disabled:text-slate-500 text-white rounded-lg transition-colors flex items-center justify-center shadow-lg"
          >
            <Send className="w-4 h-4" />
          </button>
        </form>
      </div>
    </div>
  );
}
