import { auth } from './lib/firebase';
import React, { useState, useRef, useEffect } from 'react';
import { Send, Bot, User, Loader2, Sparkles, Building2, Briefcase, CheckCircle2, Paperclip, X } from 'lucide-react';
import { collection, getDocs, addDoc, getDoc, doc, updateDoc, query, where, orderBy, setDoc } from 'firebase/firestore';
import { db } from './lib/firebase';
import ReactMarkdown from 'react-markdown';
import { useFirestore } from './hooks/useFirestore';

type Message = {
  role: 'user' | 'model';
  parts: { text: string }[];
  proposedAction?: any;
  metadata?: any;
  attachments?: { name: string }[];
  pdfBase64?: string | null;
  pdfName?: string | null;
};

export default function ChatApp() {
  const [messages, setMessages] = useState<Message[]>([
    { role: 'model', parts: [{ text: 'Olá! Sou o Assistente DP. Como posso ajudar com suas dúvidas sobre as empresas, sindicatos e rotinas de departamento pessoal hoje?' }] }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [contextData, setContextData] = useState<{empresas: any[], sindicatos: any[]}>({ empresas: [], sindicatos: [] });
  const { data: kanbanTasks } = useFirestore('kanban_tasks');
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [actionFeedback, setActionFeedback] = useState<string | null>(null);
  const [pdfFile, setPdfFile] = useState<File | null>(null);
  const [pdfBase64, setPdfBase64] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState(false);

  useEffect(() => {
    const fetchContextData = async () => {
      try {
        const empresasSnap = await getDocs(collection(db, 'empresas'));
        const empresas = empresasSnap.docs.map(d => ({ id: d.id, ...d.data() }));
        
        const sindicatosSnap = await getDocs(collection(db, 'sindicatos'));
        const sindicatos = sindicatosSnap.docs.map(d => ({ id: d.id, ...d.data() }));
        
        setContextData({ empresas, sindicatos });
      } catch (err) {
        console.error("Erro ao carregar contexto para IA:", err);
      }
    };
    fetchContextData();
  }, []);

  const scrollToBottom = () => {
    if (scrollContainerRef.current) {
      scrollContainerRef.current.scrollTop = scrollContainerRef.current.scrollHeight;
    }
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      processFile(e.target.files[0]);
    }
  };

  const processFile = (file: File) => {
    if (file.type !== 'application/pdf') {
      setActionFeedback('Por favor, envie apenas arquivos PDF.');
      setTimeout(() => setActionFeedback(null), 3000);
      return;
    }
    setPdfFile(file);
    const reader = new FileReader();
    reader.onload = (event) => {
      const base64String = (event.target?.result as string).split(',')[1];
      setPdfBase64(base64String);
    };
    reader.readAsDataURL(file);
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  const handleSend = async (e: React.FormEvent) => {
    e.preventDefault();
    if ((!input.trim() && !pdfFile) || isLoading) return;

    const userMessage: Message = { 
      role: 'user', 
      parts: [{ text: input.trim() || 'Arquivo anexado.' }],
      attachments: pdfFile ? [{ name: pdfFile.name }] : undefined
    };
    const newMessages = [...messages, userMessage];
    setMessages(newMessages);
    setInput('');
    if (textareaRef.current) {
      textareaRef.current.style.height = '120px';
    }
    setIsLoading(true);
    setActionFeedback(null);

    try {
      // Omit the first greeting from history sent to API as it wasn't actually generated by the model
      const historyToSend = newMessages.slice(1);

      // --- INÍCIO DA BUSCA DA CCT NO FRONTEND ---
      const normalizeSearchStr = (str: string) => {
        return (str || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim();
      };

      let targetSindicatoId = null;
      const normQuery = normalizeSearchStr(userMessage.parts[0]?.text || '');
      
      // Busca na empresa
      for (const emp of contextData.empresas) {
        const empNomeNorm = normalizeSearchStr(emp.nome);
        const words = empNomeNorm.split(/\s+/).filter(w => w.length >= 4 && !['ltda', 'eireli', 'me', 'epp', 's/a', 'comercio', 'servicos'].includes(w));
        if (normQuery.includes(empNomeNorm) || (words.length > 0 && words.some(w => normQuery.includes(w)))) {
          if (emp.sindicatoId) {
            targetSindicatoId = emp.sindicatoId;
            break;
          }
        }
      }
      
      // Busca no sindicato se não achou na empresa
      if (!targetSindicatoId) {
        for (const sind of contextData.sindicatos) {
          const sindNomeNorm = normalizeSearchStr(sind.nome);
          const acronymMatch = sindNomeNorm.match(/\(([a-z0-9\-]+)\)/);
          const acronym = acronymMatch ? acronymMatch[1] : '';
          const words = sindNomeNorm.split(/\s+/).filter(w => w.length >= 5 && !['sindicato', 'trabalhadores', 'empregados', 'estado', 'goias', 'regiao'].includes(w));
          if (normQuery.includes(sindNomeNorm) || (acronym && normQuery.includes(acronym)) || (words.length > 0 && words.some(w => normQuery.includes(w)))) {
            targetSindicatoId = sind.id;
            break;
          }
        }
      }

      let cctTextToSend = undefined;
      if (targetSindicatoId) {
        try {
          const cctDoc = await getDoc(doc(db, 'sindicatos', targetSindicatoId, 'cct_textos', 'vigente'));
          if (cctDoc.exists()) {
            cctTextToSend = cctDoc.data().texto_puro;
          }
        } catch (e) {
          console.error("Erro ao buscar CCT no frontend:", e);
        }
      }
      // --- FIM DA BUSCA ---

      const kanbanSnapshot = await getDocs(
        query(collection(db, 'kanban_tasks'), where('archived', '!=', true), orderBy('order'))
      );
      const fetchedKanbanTasks = kanbanSnapshot.docs.map(d => ({ id: d.id, ...d.data() }));

      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${await auth.currentUser?.getIdToken()}`
        },
        body: JSON.stringify({ 
          history: historyToSend,
          context: contextData,
          cctText: cctTextToSend,
          kanbanTasks: fetchedKanbanTasks,
          pdfBase64: pdfBase64,
          pdfName: pdfFile?.name
        })
      });

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error || 'Erro na comunicação com a IA.');
      }

      const resData = await response.json();
      
      let newModelMsg: Message = { 
        role: 'model', 
        parts: [{ text: resData.reply || resData.text || '' }],
        metadata: resData.metadata,
        pdfBase64: pdfBase64,
        pdfName: pdfFile?.name
      };

      if (resData.intents && resData.intents.length > 0) {
        newModelMsg.proposedAction = resData.intents;
      } else if (resData.proposedAction && resData.proposedAction.intent !== 'UNKNOWN') {
        newModelMsg.proposedAction = [
          {
            action: resData.proposedAction.intent,
            payload: resData.proposedAction.parameters
          }
        ];
      }

      setMessages([...newMessages, newModelMsg]);
      setPdfFile(null);
      setPdfBase64(null);
      if (fileInputRef.current) fileInputRef.current.value = '';
    } catch (error: any) {
      console.error(error);
      setMessages([...newMessages, { 
        role: 'model', 
        parts: [{ text: `Desculpe, ocorreu um erro: ${error.message}` }] 
      }]);
    } finally {
      setIsLoading(false);
      setTimeout(() => setActionFeedback(null), 4000);
    }
  };

  const handleConfirmAction = async (msgIndex: number) => {
    const msg = messages[msgIndex];
    if (!msg.proposedAction) return;

    setIsLoading(true);
    try {
      const intents = Array.isArray(msg.proposedAction) ? msg.proposedAction : [msg.proposedAction];
      
      for (const intent of intents) {
        const { action, payload } = intent;

        if (action === 'CREATE_CALENDAR_EVENT') {
          let eventDate = payload.date;
          if (typeof eventDate === 'string') eventDate = new Date(eventDate).getTime();
          // Buscar empresaNome se tiver empresaId
          let empresaNome = '';
          if (payload.empresaId) {
            const emp = contextData?.empresas?.find((e: any) => e.id === payload.empresaId);
            empresaNome = emp?.nomeFantasia || emp?.razaoSocial || '';
          }
          await addDoc(collection(db, 'calendarEvents'), {
            title: payload.title,
            type: payload.type || 'REMINDER',
            date: eventDate,
            empresaId: payload.empresaId || '',
            empresaNome: empresaNome,
            isRecurrent: false,
            status: 'ATIVO',
            createdAt: Date.now()
          });
          setActionFeedback(prev => (prev || '') + '✅ Evento criado no Calendário!\n');
        }

        else if (action === 'CREATE_CHECKLIST_RULE') {
          await addDoc(collection(db, 'checklistRules'), {
            ...payload,
            createdAt: Date.now()
          });
          setActionFeedback(prev => (prev || '') + '✅ Regra de Checklist criada!\n');
        }

        else if (action === 'CREATE_KANBAN_TASK') {
          await addDoc(collection(db, 'kanban_tasks'), {
            title: payload.title,
            status: payload.status || 'ENTRADA DE DEMANDAS',
            order: Date.now(),
            createdAt: Date.now(),
            archived: false
          });
          setActionFeedback(prev => (prev || '') + '✅ Cartão criado no Kanban!\n');
        }

        else if (action === 'UPDATE_FECHAMENTO_FOLHA') {
          if (payload.empresaId && payload.field) {
            const monthKey = payload.monthKey === 'ATUAL' || !payload.monthKey ? new Date().toISOString().slice(0, 7) : payload.monthKey;
            const docId = `${monthKey}_${payload.empresaId}`;
            
            await setDoc(doc(db, 'fechamentoFolha', docId), {
              [payload.field]: payload.value,
              monthKey,
              empresaId: payload.empresaId,
              updatedAt: Date.now()
            }, { merge: true });
            
            setActionFeedback(prev => (prev || '') + `✅ Folha da empresa atualizada (${payload.field}: ${payload.value})!\n`);
          }
        }

        else if (action === 'UPDATE_KANBAN_TASK') {
          if (payload.taskId) {
            await updateDoc(doc(db, 'kanban_tasks', payload.taskId), {
              ...payload.updates
            });
            setActionFeedback(prev => (prev || '') + '✅ Cartão atualizado no Kanban!\n');
          }
        }

        else if (action === 'GENERATE_TERMO') {
          // Salvar dados extraídos no localStorage para a tela de Termos consumir
          localStorage.setItem('@app:ai_generated_termo', JSON.stringify({
            termoId: payload.termoId,
            extractedData: payload.extractedData,
            pdfBase64: msg.pdfBase64,
            pdfName: msg.pdfName
          }));
          // Notificar que precisa navegar para a tela de Termos
          // (O componente pai App.tsx deve escutar isso e mudar o módulo)
          window.dispatchEvent(new CustomEvent('navigate-to-termos'));
          setActionFeedback(prev => (prev || '') + '✅ Preparando termo... Redirecionando para Auto Termos!\n');
        }

        else if (action === 'GENERATE_RECIBO') {
          localStorage.setItem('@app:ai_generated_recibo', JSON.stringify({
            ...payload,
            pdfBase64: msg.pdfBase64,
            pdfName: msg.pdfName
          }));
          window.dispatchEvent(new CustomEvent('navigate-module', { detail: 'recibos' }));
          setActionFeedback(prev => (prev || '') + '✅ Preparando recibo... Redirecionando!\n');
        }

        else if (action === 'CLEAN_BOLETO') {
          if (msg.pdfBase64) {
             localStorage.setItem('@app:ai_generated_boleto', JSON.stringify({
               pdfBase64: msg.pdfBase64,
               pdfName: msg.pdfName
             }));
          }
          window.dispatchEvent(new CustomEvent('navigate-module', { detail: 'boletos' }));
          setActionFeedback(prev => (prev || '') + '✅ Redirecionando para o Limpador de Boletos!\n');
        }

        else if (action === 'GENERATE_TRCT') {
          localStorage.setItem('@app:ai_generated_trct', JSON.stringify({
            ...payload,
            pdfBase64: msg.pdfBase64,
            pdfName: msg.pdfName
          }));
          window.dispatchEvent(new CustomEvent('navigate-module', { detail: 'trct' }));
          setActionFeedback(prev => (prev || '') + '✅ Preparando TRCT... Redirecionando!\n');
        }
      }

      // Hide buttons by removing proposedAction
      const newMessages = [...messages];
      newMessages[msgIndex] = { ...msg, proposedAction: undefined };
      setMessages(newMessages);

    } catch (error) {
      console.error("Erro ao executar ação:", error);
      setActionFeedback('Erro ao criar ação.');
    } finally {
      setIsLoading(false);
      setTimeout(() => setActionFeedback(null), 3000);
    }
  };

  const handleRejectAction = (msgIndex: number) => {
    const newMessages = [...messages];
    newMessages[msgIndex] = { ...messages[msgIndex], proposedAction: undefined };
    setMessages(newMessages);
  };

  return (
    <div className="flex flex-col h-full min-h-0">
      <div className="shrink-0 mb-6 flex items-center justify-between z-10 relative">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-indigo-500/20 rounded-xl">
            <Bot className="w-7 h-7 text-indigo-400" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white tracking-tight">Assistente DP</h2>
            <p className="text-sm text-slate-400">Inteligência Artificial conectada aos seus dados</p>
          </div>
        </div>
      </div>
      
      <div 
        ref={scrollContainerRef}
        className="flex-1 min-h-0 overflow-y-auto space-y-6 pr-4 scrollbar-thin scrollbar-thumb-slate-700 scrollbar-track-transparent"
      >
        {messages.map((msg, idx) => (
          <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`flex max-w-[90%] gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
              <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center mt-1 ${
                msg.role === 'user' ? 'bg-indigo-600' : 'bg-slate-800 border border-slate-700'
              }`}>
                {msg.role === 'user' ? <User className="w-4 h-4 text-white" /> : <Bot className="w-4 h-4 text-indigo-400" />}
              </div>
              <div className={`px-5 py-3.5 rounded-2xl ${
                msg.role === 'user' 
                  ? 'bg-indigo-600 text-white rounded-tr-sm' 
                  : 'bg-slate-800 text-slate-200 rounded-tl-sm shadow-sm border border-slate-700/50'
              }`}>
                {msg.role === 'user' && msg.attachments && msg.attachments.length > 0 && (
                  <div className="flex items-center gap-2 bg-indigo-500/20 px-3 py-2 rounded-lg mb-2 text-xs text-indigo-200 border border-indigo-500/30">
                    <Paperclip className="w-3.5 h-3.5" />
                    <span className="truncate max-w-[200px]">{msg.attachments[0].name}</span>
                  </div>
                )}
                {msg.role === 'model' ? (
                  <>
                    <div className="prose prose-invert prose-sm max-w-none break-words prose-p:leading-relaxed prose-pre:bg-slate-900 prose-pre:border prose-pre:border-slate-700">
                      <ReactMarkdown>{msg.parts[0].text}</ReactMarkdown>
                    </div>
                    {msg.proposedAction && (
                      <div className="mt-4 flex gap-3">
                        <button
                          onClick={() => handleConfirmAction(idx)}
                          className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-medium rounded-lg transition-colors flex items-center gap-2"
                        >
                          <CheckCircle2 className="w-4 h-4" />
                          Sim, confirmar
                        </button>
                        <button
                          onClick={() => handleRejectAction(idx)}
                          className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white text-sm font-medium rounded-lg transition-colors"
                        >
                          Não, cancelar
                        </button>
                      </div>
                    )}
                    {msg.metadata && (
                      <div className="mt-3 text-[10px] text-slate-500 font-medium">
                        Extraída após {msg.metadata.attempts} tentativa(s) pelo modelo {msg.metadata.model}.
                      </div>
                    )}
                  </>
                ) : (
                  <p className="whitespace-pre-wrap leading-relaxed">{msg.parts[0].text}</p>
                )}
              </div>
            </div>
          </div>
        ))}
        {isLoading && (
          <div className="flex justify-start">
            <div className="flex max-w-[90%] gap-3 flex-row">
              <div className="flex-shrink-0 w-8 h-8 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center mt-1">
                <Bot className="w-4 h-4 text-indigo-400" />
              </div>
              <div className="px-5 py-4 bg-slate-800 text-slate-200 rounded-2xl rounded-tl-sm shadow-sm border border-slate-700/50 flex items-center gap-2">
                <Loader2 className="w-4 h-4 animate-spin text-indigo-400" />
                <span className="text-sm font-medium text-slate-400">Processando...</span>
              </div>
            </div>
          </div>
        )}
      </div>

      <div className="shrink-0 border-t border-slate-800/50 pt-4 mt-4 relative">
        {actionFeedback && (
          <div className="absolute -top-10 left-0 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 px-3 py-1.5 rounded-lg text-xs flex items-center gap-2 animate-in fade-in slide-in-from-bottom-2">
            <CheckCircle2 className="w-3.5 h-3.5" />
            {actionFeedback}
          </div>
        )}
        {pdfFile && (
          <div className="absolute -top-12 left-0 bg-slate-800 border border-slate-700 text-slate-200 px-3 py-1.5 rounded-lg text-xs flex items-center gap-2 animate-in fade-in slide-in-from-bottom-2 shadow-lg">
            <Paperclip className="w-3.5 h-3.5 text-indigo-400" />
            <span className="truncate max-w-[150px]">{pdfFile.name}</span>
            <button onClick={() => { setPdfFile(null); setPdfBase64(null); if(fileInputRef.current) fileInputRef.current.value = ''; }} className="ml-1 hover:text-red-400">
              <X className="w-3.5 h-3.5" />
            </button>
          </div>
        )}
        <div
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
          className="relative"
        >
          {isDragging && (
            <div className="absolute inset-0 z-50 bg-indigo-500/20 border-2 border-indigo-500 border-dashed rounded-xl flex items-center justify-center">
              <span className="text-indigo-300 font-medium flex items-center gap-2">
                <Paperclip className="w-5 h-5" />
                Solte o PDF aqui
              </span>
            </div>
          )}
          <form onSubmit={handleSend} className="relative flex items-end gap-2">
            <input 
              type="file" 
              accept="application/pdf" 
              className="hidden" 
              ref={fileInputRef} 
              onChange={handleFileChange}
            />
            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              className="absolute left-2 bottom-2 p-2 text-slate-400 hover:text-indigo-400 hover:bg-slate-800 rounded-lg transition-colors flex items-center justify-center z-10"
              title="Anexar PDF"
            >
              <Paperclip className="w-5 h-5" />
            </button>
            <textarea
              ref={textareaRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  handleSend(e);
                }
              }}
              placeholder="Pergunte ou arraste um PDF..."
              className="w-full bg-slate-950 border border-slate-700 text-white rounded-xl py-3 pl-12 pr-12 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 resize-none min-h-[120px] max-h-[250px] scrollbar-thin transition-colors text-sm shadow-inner"
              style={{ height: '120px' }}
              onInput={(e) => {
                const target = e.target as HTMLTextAreaElement;
                target.style.height = '120px';
                target.style.height = Math.min(target.scrollHeight, 250) + 'px';
              }}
            />
            <button
              type="submit"
              disabled={(!input.trim() && !pdfFile) || isLoading}
              className="absolute right-2 bottom-2 p-2 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 disabled:text-slate-500 text-white rounded-lg transition-colors flex items-center justify-center shadow-lg"
            >
              <Send className="w-4 h-4" />
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
